### ISSUE TITLE
Explain the Any type in more detail

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#25] opened 2014-10-25 19:32 UTC
The PEP draft talks about `Any` as a union type, but in mypy it's actually very different from a union type. For example:

 - `List[Any]` is compatible with `List[int]` (and vice versa), but this is not true for union types.
 - A value of type `Any` can be assigned to a variable with an arbitrary type and vice versa, which is not true for union types.

I think we should be more explicit about at least some of the expected properties of the `Any` type.

**Comment by gvanrossum** [comment] 2015-01-29 19:57
Duplicate of #38 :-) Added to README.rst. Closing.

**Closed by gvanrossum** 2015-01-29 19:57 UTC
