### ISSUE TITLE
Make everything abstract and consistent

### ISSUE THREAD

**Issue by flying-sheep** [ambv/typehinting#42] opened 2015-01-16 20:24 UTC
remove `Dict`, `List`, `Set`, and `FrozenSet`.

create a new type for abstract `Set`s without mutability methods (likely similar to what `frozenset` can do) and rename `AbstractSet` to `MutableSet`.

leave `Tuple` because it has special status as “ordered collection of fixed length with possibly different types per element”

**Comment by gvanrossum** [comment] 2015-01-16 21:21
This is a duplicate of #12. Please discuss your motivation for this suggestion there.

**Closed by gvanrossum** 2015-01-16 21:21 UTC
