### ISSUE TITLE
What if a function has argument types but no return type?

### ISSUE THREAD

**Issue by JukkaL** [ambv/typehinting#37] opened 2015-01-15 06:36 UTC
The PEP draft has an example where there are argument type annotations but no return type annotation. What does it mean? Mypy currently treats the return type in a case like this as `Any`, but this is probably confusing, and it's easy to forget to give a return type. Maybe this should be disallowed?

For example, should this code be valid:

```
def f(x: int):
    return x + 1
```

There at least 4 potential approaches:

1. Treat missing return type as `Any`.
2. Treat missing return type as `None`.
3. Treat missing return type as an error (if any argument has an annotation).
4. If return type is missing but an argument has a type, infer return type automatically.

I'm inclined to support 3. I'm against 2 (because of inconsistency for functions which take no arguments, which must have an explicit `None` return type as otherwise they don't have an annotation at all) and 4 (explicit is better than implicit, implementation complexity).

**Comment by vlasovskikh** [comment] 2015-01-15 15:16
I think 1 sounds good. What if some of the arguments are not annotated?

**Comment by gvanrossum** [comment] 2015-01-15 15:54
I always assumed this would be (1), because "unannotated" means "Any" in
general.

On Thu, Jan 15, 2015 at 7:16 AM, Andrey Vlasovskikh <
notifications@github.com> wrote:

> I think 1 sounds good. What if some of the arguments are not annotated?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ambv/typehinting/issues/37#issuecomment-70100343>.
>



-- 
--Guido van Rossum (python.org/~guido)

**Comment by JukkaL** [comment] 2015-01-17 18:56
Okay, 1 is reasonable and how it currently works in mypy. Maybe the examples in the PEP should be modified to include the return value type, even if it's `None`? Otherwise, it may give the impression that leaving out the return type is generally the right thing to do, even though statically typed code generally should explicitly define return types, as the implicit `Any` types limit the type checker's effectiveness.

**Comment by gvanrossum** [comment] 2015-01-18 05:11
Agreed, the PEP should only show fully-annotated examples, except where explaining what leaving out annotations means.

**Comment by gvanrossum** [comment] 2015-03-26 17:30
Looks like a duplicate of #65

**Closed by gvanrossum** 2015-03-26 17:30 UTC
